{
  "formatVersion": "1.1",
  "component": {
    "url": "../../encoding/0.4.0-wasmjs1/encoding-0.4.0-wasmjs1.module",
    "group": "com.diglol.encoding",
    "module": "encoding",
    "version": "0.4.0-wasmjs1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "encoding.aar",
          "url": "encoding-android-0.4.0-wasmjs1.aar",
          "size": 18236,
          "sha512": "6b7243f8d6da59552948f4062dd258d6879510188fc9051e5026a6542c1ac84d101eece3dd0d55e2f44e7a343ed4949df1a83809a514a2cfca6b6dcc81fba54b",
          "sha256": "b5a8e1221a1bfdc242d6f15aa3222a17cc31b0179cb8c645effeeaa326080e4b",
          "sha1": "e385027e9deae9049ddbf1f5ec6345c7d2de6058",
          "md5": "408704356eae4e64d2d75941cd9fccaf"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "encoding.aar",
          "url": "encoding-android-0.4.0-wasmjs1.aar",
          "size": 18236,
          "sha512": "6b7243f8d6da59552948f4062dd258d6879510188fc9051e5026a6542c1ac84d101eece3dd0d55e2f44e7a343ed4949df1a83809a514a2cfca6b6dcc81fba54b",
          "sha256": "b5a8e1221a1bfdc242d6f15aa3222a17cc31b0179cb8c645effeeaa326080e4b",
          "sha1": "e385027e9deae9049ddbf1f5ec6345c7d2de6058",
          "md5": "408704356eae4e64d2d75941cd9fccaf"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "encoding-android-0.4.0-wasmjs1-sources.jar",
          "url": "encoding-android-0.4.0-wasmjs1-sources.jar",
          "size": 10157,
          "sha512": "9e07cc75e2211fd1e5dd9c28e4462dc70e049ec5a3118e4c07b65084115e16f826ff912db47b93b0dbef428cf2f57d92a3df3ab25d22dfe811431d2f49c9358d",
          "sha256": "84e239a6d86935c65f13394e31d68caa750906b3af0c29fdeb8707262cbfc582",
          "sha1": "c12200e8a7146d8c28ac3ed96c9259005d7b1d1c",
          "md5": "211b20b3a99b7f8a5817d6bb1ba544bb"
        }
      ]
    }
  ]
}
