{
  "formatVersion": "1.1",
  "component": {
    "group": "com.diglol.encoding",
    "module": "encoding",
    "version": "0.4.0-wasmjs1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "encoding-metadata-0.4.0-wasmjs1.jar",
          "url": "encoding-0.4.0-wasmjs1.jar",
          "size": 9948,
          "sha512": "4e833eac210da18ce718e0c4a1702eb0ac025987b620e55e19de9a2d44d958b95a80102fce85a0f855f79e18e6ad4e803f859302e259795e48e9df65a2ee8e1b",
          "sha256": "0fea52f77244039863fe3dfd3fd0c89364797e9a8862a3c5484c8d91ac8808af",
          "sha1": "3b277a16f43824a3f8a77d320436dccbe3e64e2b",
          "md5": "947917464c89d65a0fd5f6cb71c7e9ac"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "encoding-kotlin-0.4.0-wasmjs1-sources.jar",
          "url": "encoding-0.4.0-wasmjs1-sources.jar",
          "size": 9851,
          "sha512": "97702a9e38579351b9eea76f890a1fe4c02e2a0582319c6e8c6ced87c3961007322bc332201482f22808bc53b85dd8ae7706bb0524b77c822f9cdc3aa2238fa9",
          "sha256": "b6939442571d5f251d594ecaf98fa4ac9971a454e157865edc649e5562cb37fa",
          "sha1": "8f2e87dca618ef38235e2124e0cb7eaab3d3d25a",
          "md5": "63468aeb38195d4c0e475efb9d83247f"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../encoding-android/0.4.0-wasmjs1/encoding-android-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-android",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../encoding-android/0.4.0-wasmjs1/encoding-android-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-android",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../encoding-android/0.4.0-wasmjs1/encoding-android-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-android",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iosarm64/0.4.0-wasmjs1/encoding-iosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iosarm64/0.4.0-wasmjs1/encoding-iosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iosarm64/0.4.0-wasmjs1/encoding-iosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iossimulatorarm64/0.4.0-wasmjs1/encoding-iossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iossimulatorarm64/0.4.0-wasmjs1/encoding-iossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iossimulatorarm64/0.4.0-wasmjs1/encoding-iossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iosx64/0.4.0-wasmjs1/encoding-iosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iosx64/0.4.0-wasmjs1/encoding-iosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-iosx64/0.4.0-wasmjs1/encoding-iosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-iosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../encoding-js/0.4.0-wasmjs1/encoding-js-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-js",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../encoding-js/0.4.0-wasmjs1/encoding-js-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-js",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../encoding-js/0.4.0-wasmjs1/encoding-js-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-js",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../encoding-jvm/0.4.0-wasmjs1/encoding-jvm-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-jvm",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../encoding-jvm/0.4.0-wasmjs1/encoding-jvm-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-jvm",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../encoding-jvm/0.4.0-wasmjs1/encoding-jvm-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-jvm",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-linuxx64/0.4.0-wasmjs1/encoding-linuxx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-linuxx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-linuxx64/0.4.0-wasmjs1/encoding-linuxx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-linuxx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-macosarm64/0.4.0-wasmjs1/encoding-macosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-macosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-macosarm64/0.4.0-wasmjs1/encoding-macosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-macosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-macosarm64/0.4.0-wasmjs1/encoding-macosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-macosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-macosx64/0.4.0-wasmjs1/encoding-macosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-macosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-macosx64/0.4.0-wasmjs1/encoding-macosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-macosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-macosx64/0.4.0-wasmjs1/encoding-macosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-macosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-mingwx64/0.4.0-wasmjs1/encoding-mingwx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-mingwx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-mingwx64/0.4.0-wasmjs1/encoding-mingwx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-mingwx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvosarm64/0.4.0-wasmjs1/encoding-tvosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvosarm64/0.4.0-wasmjs1/encoding-tvosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvosarm64/0.4.0-wasmjs1/encoding-tvosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvossimulatorarm64/0.4.0-wasmjs1/encoding-tvossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvossimulatorarm64/0.4.0-wasmjs1/encoding-tvossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvossimulatorarm64/0.4.0-wasmjs1/encoding-tvossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvosx64/0.4.0-wasmjs1/encoding-tvosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvosx64/0.4.0-wasmjs1/encoding-tvosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-tvosx64/0.4.0-wasmjs1/encoding-tvosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-tvosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../encoding-wasm-js/0.4.0-wasmjs1/encoding-wasm-js-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-wasm-js",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../encoding-wasm-js/0.4.0-wasmjs1/encoding-wasm-js-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-wasm-js",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../encoding-wasm-js/0.4.0-wasmjs1/encoding-wasm-js-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-wasm-js",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosarm32/0.4.0-wasmjs1/encoding-watchosarm32-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosarm32",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosarm32/0.4.0-wasmjs1/encoding-watchosarm32-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosarm32",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosarm32/0.4.0-wasmjs1/encoding-watchosarm32-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosarm32",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosarm64/0.4.0-wasmjs1/encoding-watchosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosarm64/0.4.0-wasmjs1/encoding-watchosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosarm64/0.4.0-wasmjs1/encoding-watchosarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchossimulatorarm64/0.4.0-wasmjs1/encoding-watchossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchossimulatorarm64/0.4.0-wasmjs1/encoding-watchossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchossimulatorarm64/0.4.0-wasmjs1/encoding-watchossimulatorarm64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchossimulatorarm64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosx64/0.4.0-wasmjs1/encoding-watchosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosx64/0.4.0-wasmjs1/encoding-watchosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosx64",
        "version": "0.4.0-wasmjs1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../encoding-watchosx64/0.4.0-wasmjs1/encoding-watchosx64-0.4.0-wasmjs1.module",
        "group": "com.diglol.encoding",
        "module": "encoding-watchosx64",
        "version": "0.4.0-wasmjs1"
      }
    }
  ]
}
